### ISSUE TITLE
Don't working

### ISSUE THREAD

**Issue by AJkePo** [sj-dan/OpenSea-NFT-Stealer#18]
Traceback (most recent call last):
  File "d:\Users\******\Desktop\***\OpenSea-NFT-Stealer\opensea.py", line 71, in <module>
    data = json.loads(requests.get(f"https://api.opensea.io/api/v1/assets?order_direction=asc&offset={offset}&limit=50&collection={CollectionName}&format=json", headers=headers).content.decode())
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

???? 

i have add "Accept": "application/json"

**Comment by Freezen2** [comment]
my script was working yesterday and now it doesn't work got the same error  ^

**Comment by sj-dan** [comment]
@AJkePo A few questions. First of all, what collection are you trying to download?
