### ISSUE TITLE
[BUG] 'str' object has no attribute 'removeprefix'

### ISSUE THREAD

**Issue by ayvacs** [sj-dan/OpenSea-NFT-Stealer#31]
The script downloads 15 images from **lazy-lions** and then errors at #0016. However, it downloaded over 1,000 images from a separate collection just fine. I'm on mac, if that matters.

**Terminal output**
```
#0011:
  Data  -> [✓] (Successfully downloaded)
  Image -> [✓] (Successfully downloaded)

#0012:
  Data  -> [✓] (Successfully downloaded)
  Image -> [✓] (Successfully downloaded)

#0013:
  Data  -> [✓] (Successfully downloaded)
  Image -> [✓] (Successfully downloaded)

#0014:
  Data  -> [✓] (Successfully downloaded)
  Image -> [✓] (Successfully downloaded)

#0015:
  Data  -> [✓] (Successfully downloaded)
  Image -> [✓] (Successfully downloaded)

#0016:
  Data  -> [✓] (Successfully downloaded)
Traceback (most recent call last):
  File "main.py", line 134, in <module>
    image_url = ipfs_resolve(image_url).url
  File "main.py", line 91, in ipfs_resolve
    cid = image_url.removeprefix("ipfs://")
AttributeError: 'str' object has no attribute 'removeprefix'
```

I tried other fixes on this repo, but nothing seems to work.

**Comment by sj-dan** [comment]
Please read the setup instructions. You need Python 3.9 or above.
