### ISSUE TITLE
again trackback

### ISSUE THREAD

**Issue by micash545** [sj-dan/OpenSea-NFT-Stealer#32]
Beginning download of "xxxxxxx" collection.

Traceback (most recent call last):
  File "/Users/user/Desktop/OpenSea-NFT-Stealer-master/opensea.py", line 101, in <module>
    data = json.loads(requests.get(f"https://api.opensea.io/api/v1/assets?order_direction=asc&offset={offset}&limit=50&collection={CollectionName}&format=json", headers=headers).content.decode())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0

**Comment by B00TMan** [comment]
OpenSea now requires an API Key to access the API... :(

**Comment by svensei** [comment]
Yeah I have the same problem :(

**Comment by sj-dan** [comment]
They do not require an API key, they just put a CloudFlare rule against my script. I'm fixing this now.

**Comment by svensei** [comment]
> They do not require an API key, they just put a CloudFlare rule against my script. I'm fixing this now.

Thank you so much! <3

**Comment by dannypaton** [comment]
i think the cloudflare rule is back? lol still not working for me

**Comment by ismailox1000** [comment]
it doesn't work for me either
Traceback (most recent call last):
  File "D:\OpenSea-NFT-Stealer-master\OpenSea-NFT-Stealer-master\opensea.py", line 110, in <module>
    data = json.loads(requests.get(
  File "C:\Users\is-os\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\is-os\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\is-os\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
