### ISSUE TITLE
Script stops on ~400th item, unexpectedly...  

### ISSUE THREAD

**Issue by sepa-rater** [sj-dan/OpenSea-NFT-Stealer#39]
**Describe the bug**

everything seemed to chug along fine for about 400 images... then what might be an inconsistency in an item record?! stops the process... altogether

if this cant be fixed quickly, perhaps there a simple way to adjust the script to start on item eg 404, so as to collect all other items... me no gud coder :P cheers

**The collection you were trying to download**

https://opensea.io/collection/council-of-kingz-official

**Expected behavior**

download the image/json of the NFT

**Terminal output (please show the error that the console showed)**

#0403:
  Data  -> [✓] (Already Downloaded)
Traceback (most recent call last):
  File "D:\xxxxxxxxxx\OpenSea-NFT-Stealer-master\opensea.py", line 142, in <module>
    image = requests.get(image_url)
  File "C:\Users\xxxxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\xxxxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\xxxxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "C:\Users\xxxxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "C:\Users\xxxxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "C:\Users\xxxxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

**Comment by sj-dan** [comment]
@stealthsepa Looks like some of the later NFTs are missing `https://` at the begninning of the URL.

**Comment by cryptokarl88** [comment]
is there a work around this?

**Comment by sepa-rater** [comment]
> is there a work around this?

ya just go to the opensea item and refresh the metadata, next time you run the script if will go through that item fine... you may have to do this many times through a whole collection.
