### ISSUE TITLE
Error when running on windows 

### ISSUE THREAD

**Issue by switchmaxfx** [sj-dan/OpenSea-NFT-Stealer#45]
Getting an error on line 123.

D:\Downloads\OpenSea-NFT-Stealer-master>python opensea.py invisiblefriends

Beginning download of "invisiblefriends" collection.

Traceback (most recent call last):
  File "D:\Downloads\OpenSea-NFT-Stealer-master\opensea.py", line 123, in <module>
    data = json.loads(scraper.get(f"https://api.opensea.io/api/v1/assets?order_direction=asc{token_ids}&limit=50"
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by onestix** [comment]
Same issue on Linux

**Comment by onestix** [comment]
@sj-dan any thoughts on how we can resolve this? Thanks!

**Comment by sj-dan** [comment]
> @sj-dan any thoughts on how we can resolve this? Thanks!

This kind of error just means that you're not getting the JSON response. It could be for a number of reasons. The most probable it could just be Cloudflare misbehaving. Unfortunately, there's no 1 way to solve this error, and most the time it goes away on its own after a bit.
