### ISSUE TITLE
[BUG] Erros, can't even start

### ISSUE THREAD

**Issue by therawest** [sj-dan/OpenSea-NFT-Stealer#50]
**Describe the bug**
I followed the process for installation, installed requirements, run script and it can't even start
showing errors
https://prnt.sc/6SF4830dRA54

**Terminal output
 C:\Users\logde\OneDrive\Desktop\OpenSea-NFT-Stealer-master>py opensea.py lazy-lions

Beginning download of "lazy-lions" collection.

Traceback (most recent call last):
  File "C:\Users\logde\OneDrive\Desktop\OpenSea-NFT-Stealer-master\opensea.py", line 124, in <module>
    data = json.loads(scraper.get(f"https://api.opensea.io/api/v1/assets?order_direction=asc{token_ids}&limit=50"
  File "C:\Users\logde\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\logde\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\logde\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\logde\OneDrive\Desktop\OpenSea-NFT-Stealer-master>**
```
paste here
```

**Comment by raskitoma** [comment]
Same error, I tried to change browser User-Agent data with no luck.  Also I tried to check the url (printing the result of the dict) and it works.  Maybe is a thing related to changes on the API on opensea side

**Comment by G-Z-Ming** [comment]
![image](https://user-images.githubusercontent.com/40484256/171152464-3240b154-1cc2-406c-8887-57162a3259f3.png)

This interface now requires an API Key

**Comment by raskitoma** [comment]
@G-Z-Ming thanks for the advice.  I'm going to open a dev account and try to fix the code and share here if I can do it too...

**Comment by webcoderz** [comment]
fixed https://github.com/sj-dan/OpenSea-NFT-Stealer/pull/53
