### ISSUE TITLE
Unable to Download colletction (just creating 0029.json)

### ISSUE THREAD

**Issue by ghost** [sj-dan/OpenSea-NFT-Stealer#51]
Unable to download the boredapeyachtclub, mutant-ape-yacht-club, bored-ape-kennel-club and bored-ape-chemistry-club collection (just creating *insert number*.json) then stopping with the following output:

:\Users\chris\Desktop\OpenSea-NFT-Stealer-master>py opensea.py boredapeyachtclub

Beginning download of "boredapeyachtclub" collection.

#0029:
  Data  -> [✓] (Successfully downloaded)
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\OpenSea-NFT-Stealer-master\opensea.py", line 161, in <module>
    image = requests.get(image_url)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'ipfs://QmQnps7UF7zCBk2bsANKTuXeeuhVRhxcgWfc3AHq2B6gcc'

Successfully downloaded proof-moonbirds collection (haven't tried more)!

**Comment by sj-dan** [comment]
Fixed by d8938bf.
